#!/usr/bin/env bash
# Generate LVGL CJK subset fonts into main/fonts/.
#
# Charset: GB2312 level-1 hanzi (3755 most common, tools/fonts/cjk_common.txt)
# + CJK punctuation + fullwidth forms + common dashes/quotes/ellipsis.
# Source face: Noto Sans CJK SC Regular (OFL), tools/fonts/NotoSansCJKsc-Regular.otf
#   https://github.com/notofonts/noto-cjk  (re-download if missing)
#
# Requires node/npx. Runs lv_font_conv from npm (prompts for install).
set -euo pipefail
cd "$(dirname "$0")"

CHARS="$(cat cjk_common.txt)"
OUT=../../main/fonts
mkdir -p "$OUT"

for size in 16 20 24; do
  echo ">> font_cjk_${size} (${size}px)"
  npx lv_font_conv \
    --font NotoSansCJKsc-Regular.otf \
    --symbols "$CHARS" \
    --range 0x3000-0x303F,0xFF01-0xFF5E,0x2013-0x2026 \
    --size "$size" --bpp 4 --format lvgl \
    --lv-font-name "font_cjk_${size}" \
    -o "${OUT}/font_cjk_${size}.c"
  # The ESP-IDF LVGL component exports lvgl.h directly, not lvgl/lvgl.h.
  sed 's@#include "lvgl/lvgl.h"@#include "lvgl.h"@' \
    "${OUT}/font_cjk_${size}.c" > "${OUT}/font_cjk_${size}.tmp"
  mv "${OUT}/font_cjk_${size}.tmp" "${OUT}/font_cjk_${size}.c"
done

cat > "${OUT}/cjk_fonts.h" <<'EOF'
#pragma once
/* Generated by tools/fonts/make_cjk_fonts.sh — do not edit by hand. */
#include "lvgl.h"

LV_FONT_DECLARE(font_cjk_16);
LV_FONT_DECLARE(font_cjk_20);
LV_FONT_DECLARE(font_cjk_24);

#define UI_HAVE_CJK_FONT 1
EOF

echo "done: ${OUT}/font_cjk_{16,20,24}.c + cjk_fonts.h"
