#pragma once
/* Generated by tools/fonts/make_cjk_fonts.sh — do not edit by hand. */
#include "lvgl.h"

LV_FONT_DECLARE(font_cjk_16);
LV_FONT_DECLARE(font_cjk_20);
LV_FONT_DECLARE(font_cjk_24);

#define UI_HAVE_CJK_FONT 1
